services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '11112:8000'
    environment:
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DEV_DISABLE_SSL_VERIFY: ${DEV_DISABLE_SSL_VERIFY}
    env_file:
      - .env
    restart: unless-stopped
